offen/offen_ynh

conf/app.src
manifest.json

Update version to [v0.1.5][1]
[1]: https://github.com/offen/offen/releases/v0.1.5

Update version to v0.1.5

---

conf/app.src
manifest.json

Update version to [v0.1.6][1]
[1]: https://github.com/offen/offen/releases/v0.1.6

Update version to v0.1.6

---

conf/app.src
manifest.json

Update version to [v0.1.7][1]
[1]: https://github.com/offen/offen/releases/v0.1.7

Update version to v0.1.7

---

conf/app.src
manifest.json

Update version to [v0.1.8][1]
[1]: https://github.com/offen/offen/releases/v0.1.8

Update version to v0.1.8

---

conf/app.src
manifest.json

Update version to [v0.2.0][1]
[1]: https://github.com/offen/offen/releases/v0.2.0

Update version to v0.2.0

---

conf/app.src
manifest.json

Update version to [v0.2.1][1]
[1]: https://github.com/offen/offen/releases/v0.2.1

Update version to v0.2.1

---

conf/app.src
manifest.json

Update version to [v0.2.2][1]
[1]: https://github.com/offen/offen/releases/v0.2.2

Update version to v0.2.2

---

conf/app.src
manifest.json

Update version to [v0.2.3][1]
[1]: https://github.com/offen/offen/releases/v0.2.3

Update version to v0.2.3

---

conf/app.src
manifest.json

Update version to [v0.3.0][1]
[1]: https://github.com/offen/offen/releases/v0.3.0

Update version to v0.3.0

---

conf/app.src
manifest.json

Update version to [v0.3.1][1]
[1]: https://github.com/offen/offen/releases/v0.3.1

Update version to v0.3.1

---

conf/app.src
manifest.json

Update version to [v0.4.0][1]
[1]: https://github.com/offen/offen/releases/v0.4.0

Update version to v0.4.0

---

conf/app.src
manifest.json

Update version to [v0.4.1][1]
[1]: https://github.com/offen/offen/releases/v0.4.1

Update version to v0.4.1

---

conf/app.src
manifest.json

Update version to [v0.4.2][1]
[1]: https://github.com/offen/offen/releases/v0.4.2

Update version to v0.4.2

---

conf/app.src
manifest.json

Update version to [v0.4.3][1]
[1]: https://github.com/offen/offen/releases/v0.4.3

Update version to v0.4.3

---

conf/app.src
manifest.json

Update version to [v0.4.4][1]
[1]: https://github.com/offen/offen/releases/v0.4.4

Update version to v0.4.4

---

conf/app.src
manifest.json

Update version to [v0.6.0][1]
[1]: https://github.com/offen/offen/releases/v0.6.0

Update version to v0.6.0

---

conf/app.src
manifest.json

Update version to [v1.0.0][1]
[1]: https://github.com/offen/offen/releases/v1.0.0

Update version to v1.0.0

---

conf/app.src
manifest.json

Update version to [v1.0.1][1]
[1]: https://github.com/offen/offen/releases/v1.0.1

Update version to v1.0.1

---

conf/app.src
manifest.json

Update version to [v1.1.0][1]
[1]: https://github.com/offen/offen/releases/v1.1.0

Update version to v1.1.0

---

conf/app.src
manifest.json

Update version to [v1.2.0][1]
[1]: https://github.com/offen/offen/releases/v1.2.0

Update version to v1.2.0

---

conf/app.src
manifest.json

Update version to [v1.2.1][1]
[1]: https://github.com/offen/offen/releases/v1.2.1

Update version to v1.2.1

---

conf/app.src
manifest.json

Update version to [v1.3.0][1]
[1]: https://github.com/offen/offen/releases/v1.3.0

Update version to v1.3.0

---

conf/app.src
manifest.json

Update version to [v1.3.1][1]
[1]: https://github.com/offen/offen/releases/v1.3.1

Update version to v1.3.1

---

conf/app.src
manifest.json

Update version to [v1.3.2][1]
[1]: https://github.com/offen/offen/releases/v1.3.2

Update version to v1.3.2

---

conf/app.src
manifest.json

Update version to [v1.3.3][1]
[1]: https://github.com/offen/offen/releases/v1.3.3

Update version to v1.3.3

---

conf/app.src
manifest.json

Update version to [v1.3.4][1]
[1]: https://github.com/offen/offen/releases/v1.3.4

Update version to v1.3.4

---

conf/app.src
manifest.json

Update version to [v1.4.0][1]
[1]: https://github.com/offen/offen/releases/v1.4.0

Update version to v1.4.0

---

conf/app.src
manifest.json

Revert "Update version to v1.4.0"

---

conf/app.src
manifest.json

Update version to [v1.4.1][1]
[1]: https://github.com/offen/offen/releases/v1.4.1

Update version to v1.4.1
